const express = require('express')
const app = express()
require('express-async-errors')
const cors = require('cors')
const mongoose = require('mongoose')
const blogs = require('./controllers/blogs')
const users = require('./controllers/users')
const login = require('./controllers/login')
const tokenExtractor = require('./middlewares/tokenExtractor')
const userExtractor = require('./middlewares/userExtractor')
const {mongoUrl, PORT} = require('./utils/config')
const {logger} = require('./utils/logger')
const errorHandler = require('./middlewares/errorHandling')
// console.log(mongoUrl)
mongoose.connect(mongoUrl)
    .then(()=>logger("database connected"))
    .catch((err)=> logger("Error connecting the database",err))

app.use(cors())
app.use(express.json())
app.use('/api/login',login)
app.use('/api/users',users)
app.use(tokenExtractor)
app.use(userExtractor)
app.use('/api/blogs',blogs)


app.use(errorHandler)

module.exports = app